[package]
name = "expect-test"
version = "0.1.0"
description = "A minimal snapshot testing library"
license = "MIT OR Apache-2.0"
repository = "https://github.com/rust-analyzer/rust-analyzer"
authors = ["rust-analyzer developers"]
edition = "2018"

exclude = [".github/", "bors.toml"]

[dependencies]
once_cell = "1"
difference = "2"
